### PR TITLE
Support Xcode 9 and Swift 4.

### PR DESCRIPTION
**Pull request by ThomasLee969**

### CODE REVIEW

**Comment by svdo** [comment]
Extra kudos for updating README, thanks! 👍

**Comment by ThomasLee969** [comment]
Not at all, you might also want to update the README in `master` to mention this branch?
Thank you for creating such a nice library 😄

**Comment by svdo** [comment]
Good idea, will do. Did you try and make it so that both Swift 3 and Swift 4 are supported? I don't have time to look into that at the moment, but that we be awesome because then we wouldn't need the separate branch anymore. Basically, somehow the `ifaddrs` module map would have to be used when using this as a Cocoapod from Swift 3, and not when using it from Swift 4...

**Comment by ThomasLee969** [comment]
It seems that it can be done by not importing `ifaddrs` in Xcode 9 (swift 3.2 or higher), so that the compiler will not see `ifaddrs ` module at all.

I feel so stupid for my earlier approach…

**Comment by svdo** [comment]
Not at all, we're both learning here so that can't be called stupid as far as I'm concerned :)

**Comment by svdo** [comment]
P.S. I deleted the swift4 branch, it should no longer be needed. Please let me know if you run into issues.

**Pull request merged**
